import Dashboard from "@pages/admin/Dashboard";
import Himawari from "@pages/admin/Himawari";
import RiskAnalysis from "@pages/admin/RiskAnalysis";
import RiskV2 from "@pages/admin/RiskV2";
import TestMap from "@pages/admin/TestMap";
import Typhoons from "@pages/admin/Typhoons";
import {
  ActivityIcon,
  CircleUser,
  CloudRainWindIcon,
  FileChartColumn,
  History,
  LayoutDashboard,
  Map,
  Radar,
  Satellite,
  Siren,
  TestTubes,
} from "lucide-react";

export const ADMIN_MODULES = [
  {
    type: "item",
    // icon: LayoutDashboard,
    value: "dashboard",
    label: "Dashboard",
    link: "/admin/dashboard",
    element: <Dashboard />,
  },
  {
    type: "item",
    // icon: ActivityIcon,
    value: "risk-analysis",
    label: "Risk Analysis",
    link: "/admin/risk-analysis",
    element: <RiskV2 />,
  },
  // {
  //   type: "group",
  //   // icon: Map,
  //   value: "risk-analysis",
  //   label: "Risk Analysis",
  //   children: [
  //     {
  //       type: "item",
  //       // icon: ActivityIcon,
  //       value: "risk-analysis-local",
  //       label: "Local",
  //       link: "/admin/risk-analysis/local",
  //       element: <RiskAnalysis />,
  //     },
  //     {
  //       type: "item",
  //       // icon: ActivityIcon,
  //       value: "risk-analysis-national",
  //       label: "National",
  //       link: "/admin/risk-analysis/national",
  //       // element: <RiskIntelligence />,
  //     },
  //     {
  //       type: "item",
  //       // icon: ActivityIcon,
  //       value: "risk-analysis-6-Hours",
  //       label: "6-Hours",
  //       link: "/admin/risk-analysis/6-Hours",
  //       // element: <RiskAnalysis />,
  //     },
  //     {
  //       type: "item",
  //       // icon: ActivityIcon,
  //       value: "risk-analysis-barangay",
  //       label: "Barangay",
  //       link: "/admin/risk-analysis/barangay",
  //       // element: <RiskIntelligence />,
  //     },
  //   ],
  // },
  {
    type: "item",
    // icon: CloudRainWindIcon,
    value: "typhoons",
    label: "Typhoons",
    link: "/admin/typhoons",
    element: <Typhoons />,
  },
  {
    type: "item",
    // icon: Radar,
    value: "sensors",
    label: "Sensors",
    link: "/admin/sensors",
    // element: <SecondPage />,
  },
  {
    type: "item",
    // icon: FileChartColumn,
    value: "reports",
    label: "Reports",
    link: "/admin/reports",
    // element: <Reports />,
  },
  {
    type: "item",
    // icon: Siren,
    value: "alerts",
    label: "Alerts",
    link: "/admin/alerts",
    // element: <SecondPage />,
  },
  {
    type: "item",
    // icon: History,
    value: "history",
    label: "History",
    link: "/admin/history",
    // element: <History />,
  },
  {
    type: "item",
    // icon: CircleUser,
    value: "Admin",
    label: "Admin",
    link: "/admin/Admin",
    // element: <SecondPage />,
  },

  {
    type: "item",
    // icon: ActivityIcon,
    value: "test-map",
    label: "Test Map",
    link: "/admin/test-map",
    element: <TestMap />,
  },
  {
    type: "item",
    // icon: Satellite,
    value: "himawari",
    label: "Himawari",
    link: "/admin/himawari",
    element: <Himawari />,
  },
  {
    type: "item",
    // icon: TestTubes,
    value: "sandBox",
    label: "SandBox",
    link: "/admin/sandBox",
    // element: <SandBox />,
  },

  // {
  //   type: "group",
  //   // icon: <GlobalOutlined />,
  //   value: "maps",
  //   label: "Maps",
  //   children: [
  //     {
  //       value: "map1",
  //       label: "Map",
  //       // icon: <GlobalOutlined />,
  //       link: "/admin/maps/map1",
  //       // element: <Map />,
  //     },
  //     {
  //       value: "mapv2",
  //       label: "Mapv2",
  //       // icon: <GlobalOutlined />,
  //       link: "/admin/maps/mapv2",
  //       // element: <Mapv2 />,
  //     },
  //     {
  //       value: "weather",
  //       label: "Weather",
  //       // icon: <CloudOutlined />,
  //       link: "/admin/maps/weather",
  //       // element: <Weather />,
  //     },
  //   ],
  // },
];
