import { air, mist, speed, thermostat } from "@assets/icons";
import {
  SunLine,
  MoonStarsLine,
  SunCloudyLine,
  MoonCloudyLine,
  CloudLine,
  CloudsLine,
  CloudLightningLine,
  WetLine,
  DrizzleLine,
  ShowersLine,
  ThunderstormLine,
  TyphoonLine,
} from "@assets/weather-icons";

export const CURRENT_WEATHER = {
  temperature: "28°C",
  condition: "Cloudy",
  icon: <CloudLine className="w-30 h-30" />,
  current: [
    { name: "Wind", value: "2 kph", icon: air },
    {
      name: "Humidity",
      value: "98%",
      icon: mist,
    },
    {
      name: "Pressure",
      value: "1005 hpa",
      icon: speed,
    },
    {
      name: "Dew Point",
      value: "25°C",
      icon: thermostat,
    },
  ],
};

export const HOURLY_FORECAST = [
  {
    time: "4PM",
    icon: <SunLine className="w-18 h-18 text-gray-500" />,
    condition: "Sunny",
    precipitationChance: "0%",
    precipitationAmount: "0mm",
    temperatureWind: "34° 12 km/h",
  },
  {
    time: "5PM",
    icon: <SunCloudyLine className="w-18 h-18 text-gray-500" />,
    condition: "Partly Cloudy",
    precipitationChance: "5%",
    precipitationAmount: "0mm",
    temperatureWind: "33° 10 km/h",
  },
  {
    time: "6PM",
    icon: <CloudLine className="w-18 h-18 text-gray-500" />,
    condition: "Cloudy",
    precipitationChance: "10%",
    precipitationAmount: "0mm",
    temperatureWind: "32° 8 km/h",
  },
  {
    time: "7PM",
    icon: <CloudsLine className="w-18 h-18 text-gray-500" />,
    condition: "Mostly Cloudy",
    precipitationChance: "15%",
    precipitationAmount: "0mm",
    temperatureWind: "31° 8 km/h",
  },
  {
    time: "8PM",
    icon: <DrizzleLine className="w-18 h-18 text-gray-500" />,
    condition: "Drizzle",
    precipitationChance: "20%",
    precipitationAmount: "1mm",
    temperatureWind: "30° 6 km/h",
  },
  {
    time: "9PM",
    icon: <ShowersLine className="w-18 h-18 text-gray-500" />,
    condition: "Rain",
    precipitationChance: "45%",
    precipitationAmount: "9mm",
    temperatureWind: "29° 7 km/h",
  },
  {
    time: "10PM",
    icon: <CloudLightningLine className="w-18 h-18 text-gray-500" />,
    condition: "Thunderstorm",
    precipitationChance: "60%",
    precipitationAmount: "15mm",
    temperatureWind: "27° 15 km/h",
  },
  {
    time: "11PM",
    icon: <WetLine className="w-18 h-18 text-gray-500" />,
    condition: "Humid",
    precipitationChance: "10%",
    precipitationAmount: "0mm",
    temperatureWind: "27° 10 km/h",
  },
  {
    time: "12AM",
    icon: <MoonStarsLine className="w-18 h-18 text-gray-500" />,
    condition: "Clear Night",
    precipitationChance: "0%",
    precipitationAmount: "0mm",
    temperatureWind: "26° 5 km/h",
  },
  {
    time: "1AM",
    icon: <MoonCloudyLine className="w-18 h-18 text-gray-500" />,
    condition: "Cloudy Night",
    precipitationChance: "10%",
    precipitationAmount: "0mm",
    temperatureWind: "25° 6 km/h",
  },
];

export const DAILY_OUTLOOK = [
  {
    day: "Wednesday",
    date: "Nov 05",
    icon: <CloudLine className="w-10 h-10" />,
    condition: "Cloudy",
    high: "30°C",
    low: "24°C",
    chance: "Chance of Rain",
    windSpeedDirection: "16km",
    wind: "12 km/h",
  },
  {
    day: "Thursday",
    date: "Nov 06",
    icon: <SunCloudyLine className="w-10 h-10" />,
    condition: "Partly Cloudy",
    high: "31°C",
    low: "25°C",
    chance: "Chance of Rain",
    windSpeedDirection: "13km",
    wind: "10 km/h",
  },
  {
    day: "Friday",
    date: "Nov 07",
    icon: <ShowersLine className="w-10 h-10" />,
    condition: "Showers",
    high: "29°C",
    low: "24°C",
    chance: "Chance of Rain",
    windSpeedDirection: "14km",
    wind: "14 km/h",
  },
  {
    day: "Saturday",
    date: "Nov 08",
    icon: <ThunderstormLine className="w-10 h-10" />,
    condition: "Thunderstorm",
    high: "28°C",
    low: "23°C",
    chance: "Chance of Rain",
    windSpeedDirection: "18km",
    wind: "20 km/h",
  },
  {
    day: "Sunday",
    date: "Nov 09",
    icon: <CloudsLine className="w-10 h-10" />,
    condition: "Mostly Cloudy",
    high: "30°C",
    low: "24°C",
    chance: "Chance of Rain",
    windSpeedDirection: "11km",
    wind: "11 km/h",
  },
  {
    day: "Monday",
    date: "Nov 10",
    icon: <SunLine className="w-10 h-10" />,
    condition: "Sunny",
    high: "33°C",
    low: "26°C",
    chance: "Chance of Rain",
    windSpeedDirection: "9km",
    wind: "8 km/h",
  },
  {
    day: "Tuesday",
    date: "Nov 11",
    icon: <TyphoonLine className="w-10 h-10" />,
    condition: "Typhoon",
    high: "27°C",
    low: "23°C",
    chance: "Chance of Rain",
    windSpeedDirection: "35km",
    wind: "30 km/h",
  },
];
